### ISSUE TITLE
fix bug of guessrequester crashing on certain slot ranges

### ISSUE THREAD

**Issue by santi1234567** [migalabs/block-printer#7]
logs:

```
INFO - Retrying...
INFO - Downloading blocks 290001 to 300000...
INFO - Downloaded 9902 blocks in 42.44 seconds. Found 98 missing blocks.
ERROR - Error while backfilling: list index out of range
ERROR - Max retries reached, aborting
Reindex: False
Traceback (most recent call last):
  File "/app/load_db.py", line 181, in <module>
    main()
  File "/app/load_db.py", line 155, in main
    backfillSlots(last_slot_saved, classifier, model_folder, node_url, add_to_model, db)
  File "/app/load_db.py", line 107, in backfillSlots
    raise e
  File "/app/load_db.py", line 85, in backfillSlots
    loadSlotGuessesDatabase(
  File "/app/load_db.py", line 53, in loadSlotGuessesDatabase
    guesses = getSlotGuesses(
              ^^^^^^^^^^^^^^^
  File "/app/guessRequester.py", line 120, in getSlotGuesses
    slot = block_rewards[block_rewards_index]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
```

**Comment by santi1234567** [comment]
Bug seems to occur when there slot range ends with missing slots. Example: [https://beaconscan.com/slot/300000](https://beaconscan.com/slot/300000)
